version: 2.1
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9.1
orbs:
  heroku: circleci/heroku@0.0.8
workflows:
  heroku_deploy:
    jobs:
      - test
      - deploy:
          requires:
              - test
          filters:
            branches:
              ignore: master
jobs:
  test:
    <<: *defaults  
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install  #install node.js package
      - run: npm build
      - run:
          name: Run tests
          command: npm test
          
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          force: true
          




